name: Scala CI

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Mise en cache de SBT et Ivy
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt

      - name: Setup Scala and SBT
        uses: olafurpg/setup-scala@v11
        with:
          sbt-version: '1.9.0'

      - name: Lancer les tests
        run: sbt test
